development:
  adapter: postgresql
  encoding: unicode
  database: Places2iSola_development
  pool: 5
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: Places2iSola_test
  pool: 5
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  database: Places2iSola_production
  pool: 5
  host: 127.0.0.1
